{% set name = "elegy" %}
{% set version = "0.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elegy-{{ version }}.tar.gz
  #sha256: 1c21b2854b4c55395ec2cf5bfc110990eb67b9206168f3c4ed38dd66f9f0bb48

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.6,<3.12
    - poetry-core
    - poetry
  run:
    - cloudpickle >=1.5.0,<2.0.0
    - python >=3.6,<3.12
    - tensorboardx >=2.1,<3.0
    - treex >=0.6.5,<0.7.0
    - wandb >=0.12.10,<0.13.0

test:
  imports:
    - elegy

about:
  home: https://poets-ai.github.io/elegy
  summary: Elegy is a Neural Networks framework based on Jax and Haiku.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
